### ISSUE TITLE
Migration?

### ISSUE THREAD

**Issue by QuillLittlefeather** [M-O-S-E-S/mgm#10]
Do you have a script or something that i Can use to migrate from robust 0.8.x to simian? and not to be a pain but how do you install the new mgm on linux? the commands in the readme do not work

**Comment by mjheilmann** [comment]
Inside simian there is a folder named RobustMigration, that appears to be a c# project.  I haven't used it myself, it is provided from simian upstream.

I have always migrated through the use of oar and iar files through the opensim console.  It does not scrape and migrate user accounts, just their inventories.  If your grid is very large it will be cumbersome, but my grids have all been rather small.

The new mgm is not deployment ready.  It would normally be a new branch on the same repository, so it can be worked on without affecting the master branch, but this is a complete rewrite in a new language.  Please use mgm-defunct until we can tag a stable 2.0 on the mgm repository.
