### ISSUE TITLE
Trying to generate map tile for region

### ISSUE THREAD

**Issue by QuillLittlefeather** [M-O-S-E-S/mgm#12]
I get this isse if i try to generate a maptile in mgm console  

2255:error:{04:47:26} - Command error: System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenSim.Region.CoreModules.World.WorldMap.WorldMapModule.HandleGenerateMapConsoleCommand(String module, String[] cmdparams) in c:\User
s\root\Downloads\archive998\opensim-0.8.1-dev\OpenSim\Region\CoreModules\World\WorldMap\WorldMapModule.cs:line 1332
   at OpenSim.Framework.Console.Commands.Resolve(String[] cmd) in c:\Users\root\Downloads\archive998\opensim-0.8.1-dev\OpenSim\Framework\Con
sole\CommandConsole.cs:line 495
   at OpenSim.Framework.Console.RemoteConsole.ReadLine(String p, Boolean isCommand, Boolean e) in c:\Users\root\Downloads\archive998\opensim
-0.8.1-dev\OpenSim\Framework\Console\RemoteConsole.cs:line 140
   at OpenSim.Framework.Console.CommandConsole.Prompt() in c:\Users\root\Downloads\archive998\opensim-0.8.1-dev\OpenSim\Framework\Console\Co
mmandConsole.cs:line 757
   at OpenSim.Application.Main(String[] args) in c:\Users\root\Downloads\archive998\opensim-0.8.1-dev\OpenSim\Region\Application\Application
.cs:line 332

**Comment by mjheilmann** [comment]
Please double-check your configuration files.  That error is typically presented as an 'unable to register with the grid' error, and is between Opensim and simiangrid, but it is usually a symptom of configuration issues.

Also, confirm that you can see [simian/mgm ip]/Grid/ from your hosting machine.  It should be a blank page with 'simiangrid' written on it.

**Comment by QuillLittlefeather** [comment]
it does show simiangrid and this problem is happening with miab and on the server i set up. and it only happens if i try to use "generate map" or turn on generate map tiles true

**Comment by mjheilmann** [comment]
miab is known to work unmodified with regions on the same virtual machine.  Are these external regions, or have you reconfigured miab?

**Comment by QuillLittlefeather** [comment]
this is on a region  that i manual created outside of mgm however even in mgm with no changes i have this issue if i try to make maptiles as of right now there are no maptiles showing in the viewer .

**Comment by QuillLittlefeather** [comment]
also these are some additional errors 
17:06:07 - [WORLD MAP]: Failed generating terrain map: System.NullReferenceExcep
tion: Object reference not set to an instance of an object.
   at OpenMetaverse.Imaging.OpenJPEG.EncodeFromImage(Bitmap bitmap, Boolean loss

**Comment by mjheilmann** [comment]
Is this using mgmNode, or are you starting it manually?  mgmNode provides all configuration files for regions to startup for regions it controls.

Just a confirmation, dod you check the [ip]/Grid/ from the machine that you are starting the region from?

**Comment by QuillLittlefeather** [comment]
yah i check the ip i mean i can login to the grid and tp to the region the issue is only maps, weather i use mgm/mgmnode or manual config.

**Comment by mjheilmann** [comment]
That is outside of MGM, so I'm not sure how much help I can be.  Do you have regions on miab that are able to generate maptiles?  I can only recommend running diff against their configs, and ensuring that you are on the same version of opensim.  I cannot do anything with miab concerning how opensim developers update and modify their code after a miab has been released.

**Comment by QuillLittlefeather** [comment]
no the regions on miab also will not generate maptiles

**Comment by QuillLittlefeather** [comment]
1351:normal:{13:21:53} - [LOGHTTP]: HTTP OUT 3237 ServiceForm 'xRemoveAsset' to http://192.168.56.101/Grid/
1352:normal:{13:21:53} - [LOGHTTP]: SEND 3237: RequestMethod=xRemoveAsset&AssetID=34f22485-956d-47f1-999b-5978ebf278a2&cap=00000000-0000-000
0-0000-000000000000
1353:normal:{13:21:53} - [LOGHTTP]: RESPONSE 3237: {"Success":true}
1354:normal:{13:21:53} - [LOGHTTP]: HTTP OUT 3237 took 4ms, 1ms writing
1355:error:{13:21:53} - Command error: System.NullReferenceException: Object reference not set to an instance of an object
  at OpenSim.Region.CoreModules.World.WorldMap.WorldMapModule.HandleGenerateMapConsoleCommand (System.String module, System.String[] cmdpara
ms) [0x00000] in <filename unknown>:0 
  at OpenSim.Framework.Console.Commands.Resolve (System.String[] cmd) [0x00000] in <filename unknown>:0 
  at OpenSim.Framework.Console.RemoteConsole.ReadLine (System.String p, Boolean isCommand, Boolean e) [0x00000] in <filename unknown>:0 
  at OpenSim.Framework.Console.CommandConsole.Prompt () [0x00000] in <filename unknown>:0 
  at OpenSim.Application.Main (System.String[] args) [0x00000] in <filename unknown>:0 


ok so i see it is trying to post asset to http://192.168.56.101/Grid/ but that is not the ip address of mgm
how do i change this?

**Comment by QuillLittlefeather** [comment]
disregard that looked at wrong log file im still not sure the issue

**Comment by mjheilmann** [comment]
Have you changed the ip address of your miab instance?

Unfortunately I have yet to see a miab be completely and successfully reconfigured for a new ip address.  However, if that is the case, I can attempt to list all config file locations that it uses for you.

**Comment by QuillLittlefeather** [comment]
i see simian has its own maptile module?

[SimianGridMaptiles]
    Enabled = true
    MaptileURL = "http://158.69.115.180/Grid/"
    RefreshTime = 3600

is that conflicting with the other maptile module?

**Comment by QuillLittlefeather** [comment]
FIXED:
map service url needs to be /Grid/map.php/ not /Grid/ and generate map does not work with simian map that command was invoking the normal map generator that does not work with simian i gusse

**Comment by mjheilmann** [comment]
I dont think so.  Here are 3 sections I have in my regions' OpenSim.ini file with MGM where map tile generation is functional:

<pre>[Map]
        MapImageModule = "Warp3DImageModule"
        MaptileRefresh = "86400"</pre>

<pre>[SimianGridMaptiles]
        MaptileURL = "http://[ip]/Grid/"
        Enabled = "true"
        RefreshTime = "7200"</pre>

<pre>[MapImageService]
        MapImageServiceURI = "http://[ip]/Grid/"</pre>

where I have replaced my urls with [ip].

**Comment by QuillLittlefeather** [comment]
hmm thats odd let me retry map section again

also not sure if you know this but hg does not work with mgm created regions, manual regions hg works lol but then again im new to mgm

**Comment by mjheilmann** [comment]
I'm sorry, my web browser only just refreshed your ini file that you posed 5 hours ago.  That is a default OpenSim.ini file, not one generated by MGM.  MGM configs are programatically generated, and do not contain any comments.  Configuration files are also overwritten by mgmNode whenever you start or restart a region through MGM, so manually editing those configuration files will have no effect on your region.

Hand-rolling regions for simian connectivity is outside of MGM.  Please reference OpenSimulator and/or SimianGrid documentation for the inter-operation of those applications.

MGM was not defined with hypergrid in mind, and I do not hypergrid any grid that I install with it.  MGM was written to have a central access point to manage multiple regions without hand-deploying everything.  If you desire to manipulate everything directly, creating a simian-based grid without MGM is not difficult, and simian has its own front end with basic user management.

**Comment by QuillLittlefeather** [comment]
I guessed as much, I am working on making mgm create hg regions thats what i have been working on. I think i need to see what services depend on what. Thank you have been helpfull.
