### ISSUE TITLE
followed pdf cuases error

### ISSUE THREAD

**Issue by coryshort** [M-O-S-E-S/mgm#14]
pdf from [https://militarymetaverse.org/MIAB](https://militarymetaverse.org/MIAB)
Copy database.php.example to /var/www/mgm/server/application/contif/database.php:
sudo cp /var/www/html/mgm/server/application/config/database.php.example
/var/www/html/mgm/server/application/config/database.php

> @moses:/var/www/html$ sudo cp /var/www/html/mgm/server/application/config/database.php.example /var/www/html/mgm/server/application/config/database.php
cp: cannot stat ‘/var/www/html/mgm/server/application/config/database.php.example’: No such file or directory

when i have looked this up via ls and cd it doesnt exsist i then looked it up on here and see it isnt part of git now
how do i now get this to install as server folder no longer there

**Comment by mjheilmann** [comment]
The MIAB instructions are very old.  MOSES has switched to the Halcyon fork of OpenSimulator.  Please read the documentation in the repositories for the latest documentation

MOSES can no longer do MIAB, as the Halcyon fork of OpenSimulator currently requires windows to host the simulator process.  Please look at the repo at GitHub.com/m-o-s-e-s/moses<http://GitHub.com/m-o-s-e-s/moses> for the latest efforts at an all-in-one distribution.


On Apr 13, 2017, at 8:41 AM, coryshort <notifications@github.com<mailto:notifications@github.com>> wrote:


pdf from https://militarymetaverse.org/MIAB
Copy database.php.example to /var/www/mgm/server/application/contif/database.php:
sudo cp /var/www/html/mgm/server/application/config/database.php.example
/var/www/html/mgm/server/application/config/database.php

@moses<https://github.com/moses>:/var/www/html$ sudo cp /var/www/html/mgm/server/application/config/database.php.example /var/www/html/mgm/server/application/config/database.php
cp: cannot stat ‘/var/www/html/mgm/server/application/config/database.php.example’: No such file or directory

when i have looked this up via ls and cd it doesnt exsist i then looked it up on here and see it isnt part of git now
how do i now get this to install as server folder no longer there
