### ISSUE TITLE
Cannot approve new users

### ISSUE THREAD

**Issue by enochisg** [M-O-S-E-S/mgm#3]
I apologize in advance if I'm missing something from documentation.

When I attempt to approve users, I'm told "Error: Could not find default region"

**Comment by mjheilmann** [comment]
When a user is created, MGM sets the users home and last location to a 'default' region on your grid.  It is item mgm_hubRegion in the config file mgm/server/application/config/mgm.php
Set that to the name of a region on your grid, and that region becomes the default location of all new user accounts.

**Comment by enochisg** [comment]
Guess I glanced over that earlier. Thank you!
