### ISSUE TITLE
Cannot connect using viewer

### ISSUE THREAD

**Issue by enochisg** [M-O-S-E-S/mgm#4]
Upon adding a new grid, I add the following to the viewer as the URL: [ip address]/GridLogin

I then receive the following error: Could not add http to the grid list. Server provided broken grid info xml. Please contact support of http.

**Comment by mjheilmann** [comment]
What viewer are you using?  In Firestorm, you use the MGM ip address directly, and MGM services the get_grid_info request.

If you have to input the loginuri directly, simian requires a trailing slash, so [ip address]/GridLogin/ is correct for Simian, and should work for you.
