### ISSUE TITLE
No Default Avatar

### ISSUE THREAD

**Issue by enochisg** [M-O-S-E-S/mgm#5]
When a new account is created, they are not given a default avatar. When they wear the female outfit - regardless of gender chosen during account creation - it does not persist when they log out. How can this be remedied?

**Comment by mjheilmann** [comment]
That is outside the scope of MGM.  MGM is a management front-end for Simiangrid, which actually manages inventories, etc. of avatar accounts.  For help with dressing, please look for help with Opensim its-self.

Once you have a dressed avatar, simian can create a template of it, using simiangrid/contrib/simian/bin/avatargen.pl.  This script, when run correcly, generates a php file, that you place into simiangrid/Grid/avatar, next to Avatar.DefaultAvatar.php.  The template type (Default Avatar) is what is used for configuration options in the MGM config for male and female avatars.

**Comment by marcus73** [comment]
Hi. How to use the script perl avatargen.pl?
I've tried : 
- perl avatargen.pl -n 'moses admin'  -c 'avatar.MaleAvatar' -u 'http://192.168.0.9/GridLogin'
- perl avatargen.pl -n 'Moses Admin'  -c 'avatar.MaleAvatar' -u 'http://192.168.0.9/GridLogin'
- perl avatargen.pl -n 'Moses Admin'  -c 'avatar.MaleAvatar' -u 'http://192.168.0.9'
and so on... but dont'work.

The script answers:
301 moved permanently
at avatargen.pl line 552
malformed JSON string,neither array, object, number,string or atom at character offset 0 (before "(end of string)") at avatargen.pl line 523.

**Comment by marcus73** [comment]
I've tried :

sudo perl avatargen.pl -c TestAvatar -i '1e724e97-d413-4fab-be70-3bdb1bd13362' -u http://192.168.0.99/Grid/

and seems to work :)
Bye

**Comment by mjheilmann** [comment]
Yes, sorry, the Grid url and the grid login url are different paths.
