### ISSUE TITLE
Some small mistakes

### ISSUE THREAD

**Issue by marcus73** [M-O-S-E-S/mgm#7]
A) In the script miab.sh the line:
call(["sed", "-i", formatString, "/var/www/html/simiangrid/Grid/Public/config/config.php"])
 is wrong .
The corrected line is as follows:
call(["sed", "-i", formatString, "/var/www/html/simiangrid/GridPublic/config/config.php"])

B) In page 4 of "MIAB_Installation_Instructions_using_Virtual_Box_and_Ubuntu-141006.pdf"
Modify your apache file (/etc/apache2/sites-available/[*default.conf]), making the following changes:
1. Change your DocumentRoot to /var/www/html/mgm
sudo vi /etc/apache2/sites-available/00-default.conf
- Look for "DocumentRoot" and change the setting to "/var/www/html/mgm"....

The name of the configuration file of Apache is wrong. The name correct is "000-default.conf"

C) In your file php.ini the parameter post_max_size=1024M (default 8 Mb) but it was not specified in the instructions
There aren't references about the setting of the parameter sample interval in mgm.cfg, which is set to 30 in the version moses while in the standard is 10 ( probably for performance reasons).

D) You need to install these two packages in order to run correctly mgmNode.py and miab.sh :
python-twisted-web ( for mgmNode.py )
python-netifaces ( for miab.sh )

E) In the file mgm.php you must set the name of the default region , otherwise it is not possible to register new users ( for example : $ config [ ' mgm_hubregion ' ] = ' ABWIS ' ; )

F) In order to install Freeswitch not do:
sudo make && make install
but:
sudo make && sudo make install

G) Page 9-10 
"- Change the permission to execute: sudo chmod -x /root/miab.sh"...
is wrong.
The correct command is: 
sudo chmod +x /root/miab.sh

H) Edit simiangrid config GridLogin/config/config.php
$config['map_service'] = "[ip of webserver]/maps/";
This is not specified in your instructions but 
must be done otherwise the Map doesn't work properly.

I)
There is no information on how to create models of the avatars .
There is no information regarding the material provided in the folder Contrib

J) I suggest to set  in the file mgm.cfg the line $config[ ' email_host ' ]=' ';  in order to avoid problems if you are not using an SMTP server that works with MGM.

==============================================================================
I hope that the reporting of these errors/mistakes have been welcome .
Congratulations for the good work and thanks for sharing it .

**Comment by mjheilmann** [comment]
For others viewing this, miab.sh and the MIAB directions referred to here are not a part of MGM, but are a deployment example at http://militarymetaverse.org/miab/

**Comment by marcus73** [comment]
Errata Corrige:

H)    Edit simiangrid config Grid/config/config.php
$config["map_path"] = "/var/www/html/maps/";

Edit simiangrid config GridLogin/config/config.php
$config['map_service'] = "[ip of webserver]/maps/";

 This is not specified in your instructions but
must be done otherwise the Map doesn't work properly.
